on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
        
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    
    - name: Restore packages
      run: dotnet restore
      
    - name: build
      run: dotnet build --configuration Release /p:Version=${{ env.VERSION }} /p:ContinuousIntegrationBuild=true
      
    - name: test
      run: dotnet test --configuration Release --results-directory "artifacts/test/release" --no-build

    - name: pack
      run: dotnet pack --configuration Release /p:Version=${{ env.VERSION }} --no-build -o packages /p:ContinuousIntegrationBuild=true

    - name: Push Packages
      run: dotnet nuget push packages/**.nupkg --source https://nuget.pkg.github.com/ALTechUK/index.json --api-key ${{ env.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifacts/test
        retention-days: 5
